version: 2
project_name: mksrv

before:
  hooks:
    - go test ./...

builds:
  - id: mksrv
    main: ./cmd/mksrv
    binary: mksrv
    env: [CGO_ENABLED=0]
    goos: [linux, darwin, windows]
    goarch: [amd64, arm64]
    ignore:
      - goos: windows
        goarch: arm64
    ldflags:
      - >-
        -s -w
        -X main.version={{.Version}}
        -X main.commit={{.Commit}}
        -X main.date={{.Date}}
  - id: configd
    main: ./cmd/configd
    binary: configd
    env: [CGO_ENABLED=0]
    goos: [linux]
    goarch: [amd64, arm64]
    ldflags: ["-s -w"]

archives:
  - id: binaries
    ids: [mksrv]
    formats: [tar.gz]
    format_overrides:
      - goos: windows
        formats: [zip]
    name_template: '{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}'
  - id: configd
    ids: [configd]
    formats: [tar.gz]
    name_template: 'configd_{{ .Version }}_{{ .Os }}_{{ .Arch }}'
  - id: engine
    meta: true
    formats: [tar.gz]
    name_template: engine
    files:
      - infra/**/*
      - stacks/**/*
      - schemas/**/*

checksum:
  name_template: checksums.txt

source:
  enabled: true

release:
  draft: false
