variable "deployment" {
  description = "Decoded deployment.yaml object generated by the mksrv CLI."
  type        = any
}

variable "tenants" {
  description = "Decoded tenant map generated by the mksrv CLI."
  type        = map(any)
  default     = {}
}

variable "ssh_public_key" {
  description = "Operator SSH public key. When set, an EC2 key pair is created and attached to every host. Injected by the CLI from the workspace or the operator's ~/.ssh."
  type        = string
  default     = ""
}

variable "subnet_count" {
  description = "Public subnet count (one per AZ). The CLI sets 3 when a kind:cluster stack is assigned, 1 otherwise."
  type        = number
  default     = 1
}
