variable "deployment" {
  description = "Decoded deployment.yaml object generated by the mksrv CLI."
  type        = any
}

variable "tenants" {
  description = "Decoded tenant map generated by the mksrv CLI."
  # `map(any)` unifies every element into ONE common type: any tenant missing a
  # key another tenant has (e.g. only one tenant declaring `web:`/`forwards:`)
  # fails with "all map elements must have the same type". An explicit object()
  # with `optional()` attributes lets each tenant's shape genuinely vary. Keep
  # this in sync with internal/model.Tenant's JSON shape.
  type = map(object({
    version      = number
    id           = string
    display_name = string
    base_domain  = string
    dns_override = optional(object({
      provider = string
      zone_id  = optional(string)
      server   = optional(string)
    }))
    keycloak = object({
      realm = optional(string)
    })
    mail = optional(object({
      domains   = optional(list(string))
      inbound   = optional(bool)
      dmarc_rua = optional(string)
      hosted    = optional(bool)
      mailboxes = optional(list(object({
        address = string
        name    = optional(string)
      })))
    }))
    database = optional(object({
      postgrest        = optional(bool)
      schema           = optional(string)
      extensions       = optional(list(string))
      connection_limit = optional(number)
    }))
    stacks = list(string)
    forwards = optional(list(object({
      id        = string
      label     = string
      type      = string
      target    = string
      open      = optional(string)
      path      = optional(string)
      ssh_alias = optional(string)
    })))
    dns = optional(list(object({
      name  = string
      type  = string
      value = string
      ttl   = optional(number)
    })))
    mesh_routes = optional(list(string))
    web = optional(list(object({
      hostname   = string
      target     = string
      provider   = optional(string)
      cdn        = optional(bool)
      sso        = optional(bool)
      sso_groups = optional(list(string))
    })))
    device_limit = optional(number)
    branding = object({
      primary       = optional(string)
      secondary     = optional(string)
      logo_data_uri = optional(string)
    })
  }))
  default = {}
}

variable "ssh_public_key" {
  description = "Operator SSH public key. When set, an EC2 key pair is created and attached to every host. Injected by the CLI from the workspace or the operator's ~/.ssh."
  type        = string
  default     = ""
}

variable "subnet_count" {
  description = "Public subnet count (one per AZ). The CLI sets 3 when a kind:cluster stack is assigned, 1 otherwise."
  type        = number
  default     = 1
}

variable "host_volumes" {
  description = "Per-host dedicated EBS volumes, aggregated by the CLI from stacks' `storage:` blocks."
  type = map(list(object({
    name       = string
    gb         = number
    iops       = optional(number, 0)
    throughput = optional(number, 0)
    device     = string
  })))
  default = {}
}
