variable "deployment" {
  description = "Decoded deployment.yaml object generated by the mksrv CLI."
  type        = any
}

variable "tenants" {
  description = "Decoded tenant map generated by the mksrv CLI."
  type        = map(any)
  default     = {}
}
